name: Android CI (APK)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK packages
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          sudo mkdir -p $ANDROID_HOME/cmdline-tools
          sudo unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          sudo mkdir -p $ANDROID_HOME/cmdline-tools/latest
          sudo mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses > /dev/null
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Grant execution permission for Gradle
        run: chmod +x gradlew || true

      - name: Build Debug APK
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew --no-daemon assembleDebug
          else
            echo "Gradle wrapper missing; installing gradle via apt..."
            sudo apt-get update && sudo apt-get install -y gradle
            gradle --no-daemon assembleDebug
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
